# Generated by Django 3.2.20 on 2023-07-25 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=500)),
                ("comments", djrichtextfield.models.RichTextField(max_length=10000)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="books/",
                    ),
                ),
                ("image_alt", models.CharField(max_length=100)),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("mystery", "Mystery"),
                            ("thriller", "Thriller"),
                            ("horror", "Horror"),
                            ("historical", "Historical"),
                            ("romance", "Romance"),
                            ("dystopian", "Distopian"),
                        ],
                        default="mystery",
                        max_length=50,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
